### PR TITLE
[BUGFIX] Provide minimal serverParams for Frontend functional subrequest

### LINKED ISSUE #246: normalizedParams are not setup correctly using v11 subrequest for frontend request testing
Provide minimal serverParams array for core v11 compatible frontend subrequest, so the normalized param attributes are set through corresponding frontend middleware, which is needed for some functional tests, ex. PageTypeSuffixDecorator tests.

See https://forge.typo3.org/issues/94537

PulLReuqest: #244

### PR DESCRIPTION
**Pull request by sbuerk**
Provide minimal serverParams array for core v11 compatible frontend subrequest, so the normalized param attributes are set through corresponding frontend middleware, which is needed for some functional tests, ex. PageTypeSuffixDecorator tests.

See https://forge.typo3.org/issues/94537

Resolves #246

### CODE REVIEW

**Comment by lolli42** [comment]
Thanks for the patch.
Yeah. It's very possible some _SERVER details are not properly set up for sub requests, yet and NormalizeParams is then not initialized correctly. I roughly remember that I stumbled upon something, too, but didn't investigate in detail, since I had enough to do with other details in this area, when I created the sub request stuff
It's also possible some details of Environment are not fully correct.
This patch needs a good review and a verification core tests are still green (or need adaption) before merge. Not fully sure on when I'll find time for this, if nobody else steps in.

**Comment by sbuerk** [comment]
Thanks @lolli42 .

Yes I assumed that. I saw you added the frontend subrequest as a first thing, I thought this went under.

I had running locally the tests (unit,functional) before and after this "fix", and all was green (core tests that was on master).

For my "core patch" it was different. Before green, with theses changes:

**Comment by lolli42** [comment]
Thanks for your elaboration, Stefan!
v10 and master currently use the same TF version (we'll branch-off soon, though). Sub request handling only works with v11 (this is actually a HUGE achievement in v11 core!). v9 can be ignored.
I hope to find some time for an in-depth review soon and your comment helps to get more confidence on this patch.

**Comment by lolli42** [comment]
Verified the patch. Looks good and is the right thing to do. Note the GLOBALS['_SERVER'] assignments above will fall at some point when GU:getIndPEnv() is finally gone (we're working on this, but doesn't look as if it will be finished with v11).

**Comment by lolli42** [comment]
Tagged 6.9.0 and raised in core master. Go ahead with your core patch, Stefan!

**Pull request merged**
