### PR TITLE
[TASK] Update TYPO3 dependencies

### PR DESCRIPTION
**Pull request by romm**

### CODE REVIEW

**Comment by susannemoog** [comment]
Hey,

could you write / comment in the commit message what the problem with `^9.3` is?

**Comment by romm** [comment]
Hi @susannemoog, actually I just tested again and don't understand the behaviour I had previously:

I'm requiring TYPO3 package: `typo3/minimal:^9.5`, and launching `composer req typo3/testing-framework` gives me:

```
Using version ^5.0 for typo3/testing-framework
./composer.json has been updated
Gathering patches from patch file.
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - typo3/testing-framework 5.0.7 requires typo3/cms-core 10.*.*@dev -> satisfiable by typo3/cms-core[10.0.x-dev] but these conflict with your requirements or minimum-stability.
    - typo3/testing-framework 5.0.6 requires typo3/cms-core 10.*.*@dev -> satisfiable by typo3/cms-core[10.0.x-dev] but these conflict with your requirements or minimum-stability.
    - typo3/testing-framework 5.0.5 requires typo3/cms-core 10.*.*@dev -> satisfiable by typo3/cms-core[10.0.x-dev] but these conflict with your requirements or minimum-stability.
    - typo3/testing-framework 5.0.4 requires typo3/cms-core 10.*.*@dev -> satisfiable by typo3/cms-core[10.0.x-dev] but these conflict with your requirements or minimum-stability.
    - typo3/testing-framework 5.0.3 requires typo3/cms-core 10.*.*@dev -> satisfiable by typo3/cms-core[10.0.x-dev] but these conflict with your requirements or minimum-stability.
    - typo3/testing-framework 5.0.2 requires typo3/cms-core 10.*.*@dev -> satisfiable by typo3/cms-core[10.0.x-dev] but these conflict with your requirements or minimum-stability.
    - typo3/testing-framework 5.0.1 requires typo3/cms-core 10.*.*@dev -> satisfiable by typo3/cms-core[10.0.x-dev] but these conflict with your requirements or minimum-stability.
    - typo3/testing-framework 5.0.0 requires typo3/cms-core 10.*.*@dev -> satisfiable by typo3/cms-core[10.0.x-dev] but these conflict with your requirements or minimum-stability.
    - Installation request for typo3/testing-framework ^5.0 -> satisfiable by typo3/testing-framework[5.0.0, 5.0.1, 5.0.2, 5.0.3, 5.0.4, 5.0.5, 5.0.6, 5.0.7].


Installation failed, reverting ./composer.json to its original content.
```

I've been able to solve it by using `composer req typo3/testing-framework:^4.0`.

I still don't understand why Composer was not able to resolve dependencies correctly.

Any idea?

**Comment by sven-carstens** [comment]
Testing-Framework >= V5 requires typo3 core >= V10.
For typo3 V9 you shoudl require testing-framework in a version >= 4 < 5 as you did in your last composer require command.
So nothing to change in testing-framework itelf.

From https://github.com/TYPO3/testing-framework#tags-and-branches
Tags and branches

    Branch master is for core v10 and currently tagged as 5.x.y
    Branch 9 is for core v9 and tagged as 4.x.y
    Branch 8 is for core v8 and tagged as 1.x.y

**Comment by romm** [comment]
@sven-carstens as I said in my earlier comment I'm aware of this. What I don't understand is why Composer was not able to resolve the correct version to use for this package, depending on my requirement of  `typo3/minimal:^9.5`.

Anyway, this PR would not solve this issue though. @susannemoog feel free to close it if you want. 😉

**Comment by susannemoog** [comment]
Thanks for checking, closed :)

**Pull request closed without merging**
