### PR TITLE
[TASK] Update to PHPStan 1.7.10

### PR DESCRIPTION
**Pull request by oliverklee**
Used commands:

```bash
composer req --dev phpstan/phpstan:^1.7.7
./Build/Scripts/runTests.sh -s phpstanGenerateBaseline
```

Releases: main, 7, 6

### CODE REVIEW

**Comment by oliverklee** [comment]
Marked as WIP as there are no baseline changes and we could wait for one of the next PHPStan releases.

**Comment by lolli42** [comment]
hey. i'll abandon here and will just go with a 1.8.0 raise.

**Comment by lolli42** [comment]
note @oliverklee please don't push PR's like these when they don't add significant benefit: Those take like around half an hour to manage with backports to get right and be sure about it. I'd strive to raise phpstan and friends occassionally when needed because it gives real benefits, only.

**Comment by oliverklee** [comment]
@lolli42 Is the half hour the review time or the build time on CI? (I usually mark those PRs as draft so nobody will put time into review/merge/backports).

**Pull request closed without merging**
