### PR TITLE
[TASK] Add PHPUnit rules for PHPStan

### PR DESCRIPTION
**Pull request by oliverklee**
Also update PHPStan to the latest version.

Releases: main, 7, 6

### CODE REVIEW

**Comment by oliverklee** [comment]
This PR blocks another work-in-progress change of mine which makes the PHPDoc type annotations more specific.

**Comment by lolli42** [comment]
I guess you're already aware the config is not auto-loaded. It should be added to phpstan.neon similar like the 'include' section in core-monorepo does: https://github.com/TYPO3/typo3/blob/main/Build/phpstan/phpstan.neon
I assume you'll do that with the next patch and would go ahead and merge this patch now.

**Comment by lolli42** [comment]
I guess you're already aware the config is not auto-loaded. It should be added to phpstan.neon similar like the 'include' section in core-monorepo does: https://github.com/TYPO3/typo3/blob/main/Build/phpstan/phpstan.neon
I assume you'll do that with the next patch and would go ahead and merge this patch now.

**Review by sbuerk — APPROVED** [review]

**Comment by oliverklee** [comment]
> I guess you're already aware the config is not auto-loaded. 

I actually forgot that. Thanks for the reminder! I'll provide a PR for loading it.

**Comment by oliverklee** [comment]
Done: #366

**Pull request merged**
