### PR TITLE
[TASK] Use more native types in the test base classes

### PR DESCRIPTION
**Pull request by oliverklee**

### CODE REVIEW

**Comment by sbuerk** [comment]
in that form "main" only

**Comment by oliverklee** [comment]
> in that form "main" only

Yes, that's was I was thinking as well. :-)

**Comment by sbuerk** [comment]
> > in that form "main" only
> 
> Yes, that's was I was thinking as well. :-)

Yeah .. even no `7` backport in that way. union/intersection types not possible below php8.0/php8.1 thus not working with core v11/php7.4-php8.1 range. So maybe eventually partly.

**Comment by oliverklee** [comment]
Then let's keep this main-only.

**Review by sbuerk — APPROVED** [review]

**Pull request merged**
