### PR TITLE
[CLEANUP] Mark all PHP files as strict

### PR DESCRIPTION
**Pull request by oliverklee**

### CODE REVIEW

**Comment by lolli42** [comment]
Ok. I'll torture core CI with that change. If it goes green in v10, v11 pre-merge & nightlies, it shoud be safe. We'll see.

**Comment by lolli42** [comment]
Well, that's red.

v10:
https://review.typo3.org/c/Packages/TYPO3.CMS/+/70807/7   (patch set 7)
https://gitlab.typo3.org/typo3/CI/cms/-/pipelines/15812

v11:
https://review.typo3.org/c/Packages/TYPO3.CMS/+/70806/9   (patch set 9)
https://gitlab.typo3.org/typo3/CI/cms/-/pipelines/15811

Did not investigate deeper.

**Comment by oliverklee** [comment]
> Well, that's red.

Thanks, I'll look into it and update the PR accordingly.

**Comment by lolli42** [comment]
Any update or close PR for now for a new shot?

**Comment by lolli42** [comment]
Hey. I hope it's ok to close this PR for now for the sake of a more clean PR queue - It fails quite heavily and probably needs core work.
Feel free to push again when work continues.

**Pull request closed without merging**
